services:
  postgres:  # Database service
    image: postgres:16-alpine  
    environment:  # Database configuration
      POSTGRES_DB: thehive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # take port 5432 inside the container and make it available on port 5432 of my local machine
    volumes:
      - postgres_data:/var/lib/postgresql/data  # persist database data
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql  # initialize database schema, soldaki local, sağdaki container
      - ./backend/src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql  # populate initial data

  backend:  # My backendSpring Boot application
    build: ./backend  # Build from backend directory
    environment:  # Application configuration
      DB_HOST: postgres
      DB_NAME: thehive
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET}
      STREAM_CHAT_SECRET: ${STREAM_CHAT_SECRET}
    ports:
      - "8080:8080"  # take port 8080 inside the container and make it available on port 8080 locally
    depends_on:
      - postgres  # wait for database to start

  frontend:  # Vue.js frontend application
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8080/api
        VITE_STREAM_CHAT_API_KEY: ${VITE_STREAM_CHAT_API_KEY}
    ports:
      - "3000:80"  # map container port 80 to local port 3000
    depends_on:
      - backend  # wait for backend to start

volumes:
  postgres_data:  # needed (?) for database persistence
