spring:
  application:
    name: thehive-backend
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:thehive}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none  # schema.sql for database, şemayı değiştirmesin
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: false
    open-in-view: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:your-secret-key-change-this-in-production}
  expiration: 86400000

stream:
  chat:
    secret: ${STREAM_CHAT_SECRET:REPLACE_WITH_YOUR_STREAM_CHAT_SECRET} #bu kullanılmıyor

